name: CI / CD
on: [push, pull_request]

jobs:
  test:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build:production
      - run: npm run test:coverage
      - uses: hallee/eslint-action@1.0.3
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
